/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.parisnanterre;

public class App {
   public int addition(int x, int y ){
       return x*y;
   }
    public static void main(String[] args) {
        System.out.println("Coucou");
    }
}
