/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.parisnanterre;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test
     public void testadd00() {
        App f = new App();
       assertEquals(f.addition(3,4),7);
    }
}
